---
abstract: 'yet another github client command'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ph
no_index:
  directory:
    - inc
provides:
  App::ph:
    file: lib/App/ph.pm
    version: 0.02
requires:
  IPC::System::Simple: 0
  Pithub: 0
  Sys::Hostname: 0
  Term::ReadKey: 0
  autodie: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
